project-koku/koku-report-emailer

- Pipfile
- Pipfile.lock
- costemailer/charting.py
- costemailer/resources/CostEmailTemplate.html
- send_email.py
* Add pandas and matplotlib to create charts
* Add image attachments
* Embed images within email
> Create basic email that includes daily chart image.

- .env.dev.example
- costemailer/charting.py
- send_email.py
* Make recipients be an array of strings
* Fix charting check
* Fix dates and improve daily cost chart title
> Minor tweaks to email output.

- README.md
* Add basic architecture diagram in ascii to README
> Add simple architecture diagram

- .env.dev.example
- costemailer/charting.py
- costemailer/config.py
- costemailer/costquerier.py
- costemailer/rbac.py
- costemailer/resources/CostEmailTemplate.html
- send_email.py
* Add RBAC interaction
* Add Allow list
* Update flow to obtain cost per user in allow list
* Update email template.
> Update to utilize RBAC for cost visibility definitions and an allow list.

- costemailer/costquerier.py
- costemailer/resources/CostEmailTemplate.html
- send_email.py
* Adds monthly account breakdown
* Add jinja2 templating for row per account
> Add breakdown of accounts

- README.md
- costemailer/resources/CostEmailTemplate.html
* Update repo name in README
* Update Template resource URL
> Update repo name to use koku naming

- README.md
- costemailer/resources/CostEmailTemplate.html
* Update README
* Update template
> Update the github organization associated with the report emailer

- Dockerfile
- Makefile
- build_deploy.sh
- pr_check.sh
* Define Dockerfile
* Add app-interface build scripts
* Update Makefile for building the image
> Add build scripts and Dockerfile

- build_deploy.sh
* replace SCRIPTDIR with current directory
> Fix build image script

- send_email.py
* Loop was maintaining images from previous iterations
```
Could not attach file: [Errno 2] No such file or directory: '/tmp/tmpjzgy6qbf.png'
Traceback (most recent call last):
File "send_email.py", line 151, in <module>
os.unlink(img.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpjzgy6qbf.png'
```
> Resolve the file not found bug.

- Dockerfile
- Pipfile.lock
- deploy/clowdapp.yaml
* switch to ubi8/ubi-minimal base image
* dependency update
* switch to `template.openshift.io/v1` apiVersion in clowdapp template
> various updates

- costemailer/charting.py
- send_email.py
- Better handle potential missing data.
> Resolve missing data handling to avoid stacktrace.

- costemailer/rbac.py
- send_email.py
* obtain the organizations that data should be filtered on if rbac is configured with org units
> Add AWS org_unit support to the email tool.

- costemailer/resources/CostEmailTemplate.html
- send_email.py
* fix typo in report and variable names
> Fix typo in email report.

- .gitignore
- Pipfile
- Pipfile.lock
- costemailer/config.py
* I want to move away from an environment variable to a mounted volume from a ConfigMap
* Added a change to read a yaml file based on a default and specified by env location
> Read recipients info from config file.

- deploy/clowdapp.yaml
* Add volume
* Add volumeMount
> Load configuration from ConfigMap mounted volume

- costemailer/resources/CostEmailTemplate.html
* Remove monthly delta until https://issues.redhat.com/browse/COST-2600 is resolved
> Remove invalid delta while being debugged by dev team.

- costemailer/resources/CostEmailTemplate.html
- send_email.py
* Order output by largest delta value
* Color positive delta values red
> Updates for styling and ordering requests.

- costemailer/costquerier.py
- costemailer/resources/CostEmailTemplate.html
- send_email.py
* Gather all OUs
* Create back references dict
* Collect account-to-OU association
* Collect ou-to-ou association and levels
* Sum costs for each level
* Update HTML to provide tables within tables
> Organize email report by OU

- send_email.py
* Fix bug where no accounts are found.
> Handle case when no accounts are found.

- costemailer/resources/CostEmailTemplate.html
* remove org id (was not used by consumers)
* Change monthly to month-to-date per request
> Remove org id and update column wording

- send_email.py
* Update email subject line with AWS
> Update email subject line with AWS

- costemailer/reporting/aws.py
- costemailer/reporting/openshift.py
- send_email.py
* Enable multiple reports for a user and config based filtering of AWS data.
> Enable multiple reports for a user and config based filtering of AWS data.

- send_email.py
* Support cc property in reports object
> Support cc property in reports object.

- costemailer/__init__.py
- costemailer/reporting/aws.py
- costemailer/resources/AwsCostEmailTemplate.html
- send_email.py
* Enable ordering choice and fix totaling bug
> Enable ordering choice and fix totaling bug

- costemailer/costquerier.py
- costemailer/email.py
- costemailer/reporting/aws.py
- costemailer/reporting/openshift.py
* Create csv files and attach to email for AWS and CSV.
> Attach CSV output to emails.

- costemailer/__init__.py
- costemailer/reporting/aws.py
- costemailer/reporting/openshift.py
- costemailer/resources/AwsCostEmailTemplate.html
- send_email.py
* control how detailed the email is
> Limit org levels and number of accounts per org in emails

- costemailer/reporting/aws.py
> Fix org duplicate bug.

- costemailer/reporting/openshift.py
- costemailer/resources/OpenShiftCostEmailTemplate.html
* Grab service costs for each of the Openshift projects and display the costs
> Add AWS spend to Openshift emails.

- costemailer/__init__.py
- costemailer/config.py
- costemailer/reporting/ibm.py
- costemailer/resources/IBMCloudCostEmailTemplate.html
- send_email.py
* Add email template
* Add configuration to obtain the IBM Cloud API Key
* Add email report method for IBM report type
* Add logic to build email report for IBM Cloud
> Add cost reporting for IBM Cloud

- costemailer/reporting/ibm.py
- costemailer/resources/IBMCloudCostEmailTemplate.html
* Request resilience
* Work around IBM enterprise accounts list issue
> Update IBM Cloud cost emails to include discounted costs

- costemailer/costquerier.py
- costemailer/reporting/aws.py
- costemailer/resources/AwsCostEmailTemplate.html
- send_email.py
* Add report view feature to allow for OU or Cost Center reports
* Query for list of cost centers
* Allow filtering cost centers
* Get daily cost filtered by cost centers
* For each cost center get monthly costs grouped by accounts
* Create CSV for output data
* Enable email template creation based on view type
* Update HTML cost email template
> Add AWS Cost Center email support

- costemailer/resources/AwsCostEmailTemplate.html
* Add thin border between groupings
* indent accounts
* rename account alias to account name
> Minor style updates.

- costemailer/reporting/ibm.py
* Add check for zero spend emails
> Skip sending IBM Cloud emails if there has been no spend

- costemailer/reporting/aws.py
- costemailer/reporting/ibm.py
- costemailer/reporting/openshift.py
- send_email.py
* Allow users to add helpful title suffix info
> Add support for title suffix to a report

- costemailer/reporting/aws.py
* Drop OU filter if using filtered cost center
> Update for cost center filter fix

- costemailer/__init__.py
- costemailer/costquerier.py
- costemailer/email.py
- costemailer/rbac.py
- costemailer/reporting/__init__.py
- costemailer/reporting/azure.py
- costemailer/resources/AzureCostEmailTemplate.html
- send_email.py
* Add html file
* Add endpoints
* Configure setup for azure requests and email generation
> Add cost emails for Microsoft Azure

- costemailer/__init__.py
- costemailer/costquerier.py
- costemailer/rbac.py
- costemailer/reporting/__init__.py
- costemailer/reporting/gcp.py
- costemailer/resources/GCPCostEmailTemplate.html
- send_email.py
* Add html file
* Add endpoints
* Configure setup for gcp requests and email generation
> Add cost emails for Google Cloud Platform

- costemailer/reporting/azure.py
- costemailer/resources/AzureCostEmailTemplate.html
* Use newly added subscription names
* Provide both guid and name in csv file
> Use Azure Subscription Names in emails

- costemailer/reporting/aws.py
* Add field name to CSV writer.
> Support org_unit in case where OU report exists but some accounts aren't in an OU

- .pre-commit-config.yaml
- Dockerfile
- Pipfile
- Pipfile.lock
- costemailer/config.py
- costemailer/costquerier.py
- costemailer/email.py
- costemailer/rbac.py
- costemailer/reporting/aws.py
* Add Config variables for service account support
* Add header creation for service account or basic auth
* Add mechanism to obtain service account token
* Update API flows to use headers for auth support instead of basic auth directly.
> Add support for service account flow for rbac and cost mgmt queries

- deploy/clowdapp.yaml
* update clowd app and secret.
> Add service account info to cloud app

- costemailer/rbac.py
* prefer service account auth even if basic auth credentials are present.
> Default to using service account auth

- costemailer/__init__.py
- costemailer/costquerier.py
- costemailer/email.py
- costemailer/reporting/__init__.py
- costemailer/reporting/openshift.py
- costemailer/resources/OpenShiftRecommendationEmailTemplate.html
* Add template file for OpenShift recommendations
* Update openshift flow to send both a cost report and recommendations report
> Generate OCP container recommendations email

- costemailer/resources/OpenShiftRecommendationEmailTemplate.html
* Had duplicate Requests Memory on needed to be CPU.
> Fix typo in recommendations report

- .dockerignore
- build_deploy.sh
* create tmp dir for build-deploy
* add .dockerignore file
> [COST-4897] create tmp dir for build-deploy

- costemailer/reporting/openshift.py
Add missing space between value and unit format.
> Fix spacing in memory output

- deploy/clowdapp.yaml
Switch to the image created by Konflux by default
> Update default image
